//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    using Game.Data;
    using SQLite4Unity3d;
    
    
    [Serializable()]
    public class Dial
    {
        
        // Id
      [PrimaryKey] 
        public double Id {get;set;}
        // 名字
       public string Name {get;set;}
        // 是否显示名字
       public double ShowName {get;set;}
        // Icon路径
       public string Icon {get;set;}
        // 转盘值
       public List<string> Value {get;set;}
        // 是否是新增
       public double DefaultAdd {get;set;}

        public int Count { get; set; }
    }
}
